<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/18 20:59:37
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 3,
  'app_max_jobs_on_category' => 20,
));
