<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/18 17:39:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
